### ISSUE TITLE
rss feeds

### ISSUE THREAD

**Issue by cnvo** [anggadarkprince/infogue#8]

**Comment by anggadarkprince** [comment]
For now I build REST API with json format, hmm I think I should build RSS or Atom too..

**Comment by cnvo** [comment]
I noticed the REST API you've built out, and that's fantastic. RSS is widely used verses Atom, but Atom has some cool features as well.

**Comment by anggadarkprince** [comment]
I have added feed with RSS and Atom format at commit [#f0a3b20](https://github.com/anggadarkprince/infogue/commit/f0a3b20d953f3ea43b060609eb5c638b7368d7d8)
